services:
  api:
    build:
      context: .
      args:
        - PORT=${PORT}
        - MONGO_URI=${MONGO_URI}
        - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:4200}
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:4200}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
  # db_test:
  #   image: mongo
  #   container_name: test
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: test
